const localization = {
  HELLO: 'Hello',
  TITLE: 'Title',
  AGE: 'Age',
  GENRES: 'Genres',
  GRAPHICS: 'Graphics',
  RELEASE_DATE: 'Release date',
  DESCRIPTION: 'Description',
  ADD: 'Add',
  EDIT: 'Edit',
  POSTER: 'poster',
  LINK_TO_YT_TRAILER: 'Link to YT trailer',
  ADD_PICTURE_FOR_POSTER: 'Add picture for poster',
  DELETE: 'Delete',
  ARE_YOU_SURE: 'Are you sure?',
  CLOSE: 'Close',
  YES_I_AM: 'Yes, I am',
  NO_I_AM_NOT: 'No, I am not',
  NAV_CREATE: 'CREATE',
  NAV_POSTER: 'POSTER',
  NAV_HOME: 'HOME',
  LOGIN: 'Login',
  COMPANY_LOGO: 'Company logo',
  EXIT_TO_PROFILE: 'Exit to profile',
};
export default localization;
